# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/willsdw04@gmail.com/retails-pipeline")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM retails.dwh-retails.sample_trips_retails_pipeline"))

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM retails.source.products LIMIT 5;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM retails.source.users LIMIT 5;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM retails.source.reviews LIMIT 5;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM retails.source.orders LIMIT 5;

# COMMAND ----------

display(spark.sql("SELECT * FROM retails.`dwh-retails`.invalid_products_data LIMIT 5"))

# COMMAND ----------

display(spark.sql("DESCRIBE retails.`dwh-retails`.stg_users"))

# COMMAND ----------


